[
  {
    "repo": "Render",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Supabase",
    "nextVersion": "latest",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": true,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "npm",
    "sizeMB": 4,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC_Content",
    "nextVersion": "15.1.6",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "npm",
    "sizeMB": 12,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YY-Mgmt",
    "nextVersion": "15.1.7",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "ewm",
    "nextVersion": "^13.5.2",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": true,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "npm",
    "sizeMB": 17,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Docker_stack",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 77,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-CodeX",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "sizeMB": 9,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "markdown",
    "nextVersion": "^13.0.6",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": true,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "nextjs-ai-chatbot",
    "nextVersion": "15.3.0-canary.31",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC3-management",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "AI-platform",
    "nextVersion": "15.4.2",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "pbzz",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 139,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YY-Medical",
    "nextVersion": "^14.0.4",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 10,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "--hz",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "yyyp",
    "nextVersion": "15.2.5",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "npm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YY-Chatbot-B2",
    "nextVersion": "15.0.3-canary.2",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-0009",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "chanbot",
    "nextVersion": "15.3.0-canary.31",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Qwen3-Coder-30B-A3B",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC-EasyVizAI",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC-Render",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 20,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Edu-ai-question-bank",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YanYu-Cloud-Cube-App",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "ProteinLM",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "LocalAI",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CodeGeeX4",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "WebRL",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "GLM-4-Voice",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CogVideo",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "next.js-1",
    "nextVersion": "workspace:*",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "jest",
    "hasCI": true,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 284,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "P-tuning",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "gradio",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": true,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 219,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "P-tuning-v2",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "AgentTuning",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "zhou-AI",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 0,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YanYuCloudCube",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 0,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "EasyViz-AI",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 1,
    "packageManager": "",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "jiyuan",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 1,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Management",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 1,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "ZhiHu",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 1,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "AI-Learning-Platform",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 1,
    "packageManager": "pnpm",
    "sizeMB": 27,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Cudaqx",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 2,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Mana-1",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 2,
    "packageManager": "pnpm",
    "sizeMB": 8,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YanYuCloud-README",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Awesome-copilot",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 3,
    "packageManager": "npm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Codeql",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC3_AI",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "pnpm",
    "sizeMB": 16,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYltd-Brew",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "github-mcp-server",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-Nexus",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC_Smart_City_Platform",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "pnpm",
    "sizeMB": 17,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Penpot",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 3,
    "packageManager": "yarn",
    "sizeMB": 531,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "pytorch",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "tensorflow",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 3,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "AutoGPT",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 4,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "langflow",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 4,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Flowise",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 4,
    "packageManager": "pnpm",
    "sizeMB": 65,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "streamlit",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 4,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "GLM-GPT-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 4,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "flink",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 4,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "MediNexus-",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 6,
    "packageManager": "pnpm",
    "sizeMB": 27,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "modelscope",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 7,
    "packageManager": "",
    "duplicationCandidate": true
  },
  {
    "repo": "OPENvpn",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 7,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "directus",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 7,
    "packageManager": "pnpm",
    "sizeMB": 35,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "goose",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 7,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "GolangChessAI",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 8,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yy-nettrack",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 8,
    "packageManager": "pnpm",
    "sizeMB": 17,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Continue",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 9,
    "packageManager": "npm",
    "sizeMB": 1011,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Install-Mixpanel-",
    "nextVersion": "^14.2.28",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": true,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 9,
    "packageManager": "npm",
    "sizeMB": 1120,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYltd-Kolors",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Vertex-ai-creative-studio",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYltd-documentation",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": true,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "jest",
    "hasCI": true,
    "lastCommitDays": 10,
    "packageManager": "npm",
    "sizeMB": 21,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC3-AI",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC-00010",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Integrations-Page",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YY-AI",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 10,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-Learning-Hub",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "jest",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 27,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-Smart-Business-Center",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 5,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Cloud-JY",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 7,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Home-Data-Service-Platform",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 6,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "NetTrack",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-DeepStack",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-00009",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC-00008",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YanYu-Cloud-Sharing-E-center",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 16,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "ZYOYO",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 9,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Nextra",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 10,
    "packageManager": "pnpm",
    "sizeMB": 44,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "vite-react",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 10,
    "packageManager": "",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Earthengine-api",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 11,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YanYu-Cloud-DeepStack",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 13,
    "packageManager": "pnpm",
    "sizeMB": 4,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "hello-genai",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 14,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Emby.Releases",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 15,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "highlight",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 16,
    "packageManager": "yarn",
    "sizeMB": 764,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Gemini-cli",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": true,
    "lastCommitDays": 16,
    "packageManager": "npm",
    "sizeMB": 16,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "music",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": false,
    "lastCommitDays": 18,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YY-Y",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "jest",
    "hasCI": false,
    "lastCommitDays": 18,
    "packageManager": "pnpm",
    "sizeMB": 10,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "actions",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 18,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YanYu-E",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 20,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "compose-for-agents",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 23,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "vscode-extension",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 24,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yyc3-gpu-builder",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 25,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "ZY-ZhiHu",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 30,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Skandha",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": true,
    "lastCommitDays": 30,
    "packageManager": "yarn",
    "sizeMB": 7,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "v0-platform",
    "nextVersion": "15.4.2",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 32,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "go-sdk-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 32,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Docker-Mcp",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 42,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "llama.cpp",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 48,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "mlx-lm",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 49,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Docker-hub-mcp",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 49,
    "packageManager": "npm",
    "sizeMB": 14,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "JINlan",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "jest",
    "hasCI": false,
    "lastCommitDays": 52,
    "packageManager": "pnpm",
    "sizeMB": 17,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "PaddleHub",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 64,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "ollama",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 66,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "ly-cscp",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 68,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYCC",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 71,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-yishu",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 75,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "95558api",
    "nextVersion": "14.2.16",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": true,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 76,
    "packageManager": "pnpm",
    "sizeMB": 5,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YanYu-DeepStack",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 77,
    "packageManager": "pnpm",
    "sizeMB": 4,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "mcp-server",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 79,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yycloud-c",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 82,
    "packageManager": "pnpm",
    "sizeMB": 11,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 82,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Qwer3-Code",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 82,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-Render",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 85,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-vite",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": true,
    "lastCommitDays": 85,
    "packageManager": "pnpm",
    "sizeMB": 44,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YanYu-Server",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 85,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-00002",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 85,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-onlook",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": true,
    "lastCommitDays": 86,
    "packageManager": "",
    "sizeMB": 46,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYC-00001",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 86,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yanyu-test-project",
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 89,
    "packageManager": "",
    "sizeMB": 1,
    "duplicationCandidate": true,
    "recommendedAction": ""
  },
  {
    "repo": "YYIC-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 90,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yyy-fun",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 91,
    "packageManager": "pnpm",
    "sizeMB": 16,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "DateTimeExtensions",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 93,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-Mac",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 95,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Next-AI",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 96,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Emby.AutoOrganize",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 102,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YanYu-Developer-Tools",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 103,
    "packageManager": "pnpm",
    "sizeMB": 5,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Add-Webhook",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 106,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYY-API-OS",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 108,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YanYu-ltd",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 108,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY--API",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 108,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "deepseek-iAI-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 108,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "-API-",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 109,
    "packageManager": "pnpm",
    "sizeMB": 4,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "My-OS",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 110,
    "packageManager": "pnpm",
    "sizeMB": 22,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YY-Model",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 113,
    "packageManager": "",
    "duplicationCandidate": true
  },
  {
    "repo": "limei",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 113,
    "packageManager": "pnpm",
    "sizeMB": 20,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Vercel-AI-SDK",
    "nextVersion": "15.0.0-canary.23",
    "usesTypeScript": false,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": true,
    "lastCommitDays": 114,
    "packageManager": "pnpm",
    "sizeMB": 79,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YanYu-CloudHub-WebBoard",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 116,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY--",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 116,
    "packageManager": "pnpm",
    "sizeMB": 6,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YanYu-Cloud-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 117,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CloudNexus-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 117,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "24_Mechanical_Style",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 120,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "next.js",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 124,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-1",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 124,
    "packageManager": "pnpm",
    "sizeMB": 13,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "ERNIE",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 124,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "xuperchain",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 124,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "liangzi",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 124,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "baidu",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 124,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "co-mgmt",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 125,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "nextjs-template",
    "nextVersion": "^15.3.1",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "jest",
    "hasCI": false,
    "lastCommitDays": 131,
    "packageManager": "npm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "G-Nexus-AI",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 133,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "GLM-4",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 133,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Neuxs-AI-YiPin",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 133,
    "packageManager": "pnpm",
    "sizeMB": 11,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "zhiku",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 133,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yy-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 133,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "md",
    "nextVersion": "15.2.4",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 136,
    "packageManager": "pnpm",
    "sizeMB": 2,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "e-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 138,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yy-yy",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 138,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Next.js--",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": true,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 140,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "B-agent",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 142,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "zuoyou",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 142,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "yy-hnit",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 147,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CogAgent",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 147,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "95558-mt",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 148,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "G--",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 148,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "-",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 148,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "G-M",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 148,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YY-yyhnit",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 149,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "shiki-stream",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "vitest",
    "hasCI": true,
    "lastCommitDays": 149,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "CogView4",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 153,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Emby.Plugins.Anime",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 167,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "YYC-Video",
    "nextVersion": "latest",
    "usesTypeScript": true,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 182,
    "packageManager": "",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "YYltd-vue",
    "nextVersion": "",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 183,
    "packageManager": "pnpm",
    "sizeMB": 1,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "gh-copilot",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 200,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "NaturalCodeBench",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 320,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "MediaPortalTVPlugin",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 326,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "AutoWebGLM",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 336,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "DeepSeek-V2",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 338,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "VisualGLM-6B",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 371,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CodeGeeX",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 382,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "libunity",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 386,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CodeGeeX2",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 415,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "ChatGLM-6B",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 429,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Doc",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 448,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CogVLM",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 457,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Megatron-LM",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 480,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Segment-ai-copilot",
    "nextVersion": "14.1.3",
    "usesTypeScript": true,
    "eslintConfigured": true,
    "prettierConfigured": false,
    "hasAppDir": true,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 521,
    "packageManager": "pnpm",
    "sizeMB": 3,
    "duplicationCandidate": false,
    "recommendedAction": ""
  },
  {
    "repo": "Emby",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 536,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Rust-web3",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 575,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "CogDL",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 575,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "Emby.ApiClient",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 629,
    "packageManager": "",
    "duplicationCandidate": false
  },
  {
    "repo": "GLM-WD",
    "hasPackage": false,
    "nextVersion": "",
    "usesTypeScript": false,
    "eslintConfigured": false,
    "prettierConfigured": false,
    "hasAppDir": false,
    "pageRouterOnly": false,
    "testFramework": "",
    "hasCI": false,
    "lastCommitDays": 665,
    "packageManager": "",
    "duplicationCandidate": false
  }
]